name: aws-deploy-static-content

on:
  workflow_call:
    inputs:
      repository:
        description: GitHub repo to fetch static assets from (format = org/repo)
        required: true
        type: string

      aws-s3-bucket:
        description: Target AWS S3 bucket name
        required: true
        type: string

      aws-region:
        description: AWS region to use
        required: false
        default: "eu-west-1"
        type: string

      cloudfront-distribution:
        description: CloudFront distribution ID to invalidate after sync
        required: true
        type: string

    secrets:
      aws-access-key-id:
        description: AWS Access Key ID
        required: true

      aws-secret-access-key:
        description: AWS Secret Access Key
        required: true

      pat-github:
        description: GitHub Personal Access Token
        required: true

jobs:
  aws-deploy-static-content:
    name: aws-deploy-static-content
    runs-on: ubuntu-latest

    steps:
      - name: Checkout static asset repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.pat-github }}
          path: workflow/repository
          fetch-depth: 0

      - name: Sync to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ inputs.aws-s3-bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
          AWS_REGION: ${{ inputs.aws-region }}
          SOURCE_DIR: workflow/repository

      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ inputs.cloudfront-distribution }}
          PATHS: "/*"
          AWS_REGION: ${{ inputs.aws-region }}
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
